Vue update
Picovoice/picovoice pull request #423
Opened 2022-08-26 07:35 UTC by laves

2022-08-26 16:02 UTC, ErisMik approved these changes

2022-08-26 16:39 UTC, ksyeo1010 approved these changes

2022-08-26 18:47 UTC, mrrostam approved these changes

2022-08-30 20:57 UTC, ksyeo1010 requested changes

2022-08-30 20:57 UTC, ksyeo1010 commented on README.md
> +npm install @picovoice/picovoice-vue
```suggestion
npm install @picovoice/picovoice-vue @picovoice/web-voice-processor
```

2022-08-30 20:57 UTC, ksyeo1010 commented on README.md
> +yarn add @picovoice/picovoice-vue
```suggestion
yarn add @picovoice/picovoice-vue npm install @picovoice/picovoice-vue @picovoice/web-voice-processor
```

2022-08-30 20:57 UTC, ksyeo1010 commented on demo/vue/README.md
mention about wokringin vue2

2022-08-30 20:57 UTC, ksyeo1010 commented on sdk/vue/README.md
> +yarn add @picovoice/picovoice-vue
```suggestion
yarn add @picovoice/picovoice-vue @picovoice/web-voice-processor
```

2022-08-30 20:57 UTC, ksyeo1010 commented on sdk/vue/README.md
> +npm install --save @picovoice/picovoice-vue
```suggestion
npm install --save @picovoice/picovoice-vue @picovoice/web-voice-processor
```

2022-08-30 23:03 UTC, ksyeo1010 approved these changes

2022-08-31 22:46 UTC, merged